apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/Jasviers/homelab'
    targetRevision: HEAD
    path: services/kubevip
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-vip
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
