apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseerr-config
  namespace: media
  labels:
    app.kubernetes.io/name: jellyseerr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 2Gi
