---
- name: Stop k3s service (control-plane)
  systemd:
    name: k3s
    state: stopped
  when: inventory_hostname in groups['k3s_control_plane']
  failed_when: false

- name: Stop k3s-agent service (workers/IA)
  systemd:
    name: k3s-agent
    state: stopped
  when: inventory_hostname not in groups['k3s_control_plane']
  failed_when: false

- name: Run k3s uninstall script (control-plane)
  shell: /usr/local/bin/k3s-uninstall.sh
  when: inventory_hostname in groups['k3s_control_plane']
  args:
    removes: /usr/local/bin/k3s-uninstall.sh

- name: Run k3s-agent uninstall script (workers/IA)
  shell: /usr/local/bin/k3s-agent-uninstall.sh
  when: inventory_hostname not in groups['k3s_control_plane']
  args:
    removes: /usr/local/bin/k3s-agent-uninstall.sh

- name: Remove k3s directories
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - /etc/rancher
    - /var/lib/rancher
    - /var/log/pods
    - /var/log/containers
    - /etc/cni/net.d

- name: Remove leftover Cilium network interfaces
  command: ip link delete {{ item }}
  loop:
    - cilium_host
    - cilium_net
    - cilium_vxlan
  register: cilium_iface_del
  failed_when: false
  changed_when: cilium_iface_del.rc == 0
