apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-data
  namespace: whisper
  labels:
    app.kubernetes.io/name: whisper
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 5Gi
