apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: Kustomize

resources:
  - namespace.yml
  - csi-driver.yml
  - controller.yml
  - node.yml
  - storage-class.yml
  - externalsecret-client-info.yml
