apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: radarr-config
  namespace: media
  labels:
    app.kubernetes.io/name: radarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  volumeName: pvc-3c32058b-ca85-41b7-8a8c-a6cc9396a112
  resources:
    requests:
      storage: 2Gi
