variable "proxmox_url" {
  type        = string
  description = "URL de la API de Proxmox, por ejemplo https://pve.example.com:8006/api2/json."
}

variable "proxmox_username" {
  type        = string
  description = "Usuario de Proxmox, incluyendo el token id si aplica, por ejemplo root@pam!packer."
}

variable "proxmox_token" {
  type        = string
  sensitive   = true
  description = "Secret del token de Proxmox."
}

variable "proxmox_node" {
  type        = string
  description = "Nodo Proxmox donde se construye la plantilla."
}

variable "storage_pool" {
  type        = string
  description = "Storage pool de Proxmox para el disco principal."
  default     = "local-lvm"
}

variable "network_bridge" {
  type        = string
  description = "Bridge de red del host Proxmox."
  default     = "vmbr0"
}

variable "template_name" {
  type        = string
  description = "Nombre de la plantilla final en Proxmox."
  default     = "ubuntu26-template"
}

variable "template_description" {
  type        = string
  description = "Descripcion visible en Proxmox."
  default     = "Ubuntu 26 template generated by Packer"
}

variable "vm_name" {
  type        = string
  description = "Nombre temporal de la VM durante el build."
  default     = "ubuntu26-template"
}

variable "vm_id" {
  type        = number
  description = "VMID opcional para la VM temporal."
  default     = null
}

variable "ubuntu_iso_url" {
  type        = string
  description = "URL del ISO de Ubuntu 26 (live server)."
  default     = "https://releases.ubuntu.com/26.04/ubuntu-26.04-live-server-amd64.iso"
}

variable "ubuntu_iso_file" {
  type        = string
  description = "Archivo local del ISO de Ubuntu 26. Si se especifica, se ignora ubuntu_iso_url."
  default     = "ubuntu-26.04-live-server-amd64.iso"
}

variable "ubuntu_iso_checksum" {
  type        = string
  description = "Checksum del ISO de Ubuntu Server 26.04, por ejemplo sha256:...."
}

variable "boot_iso_storage_pool" {
  type        = string
  description = "Storage pool de Proxmox donde se guarda el ISO generado a partir de cd_content."
  default     = "local"
}

variable "boot_iso_download_pve" {
  type        = bool
  description = "Si true, el nodo Proxmox descarga el ISO de arranque en lugar de hacerlo Packer. Recomendado para evitar problemas de descarga TLS desde el host de Packer."
  default     = false
}

variable "disk_size" {
  type        = string
  description = "Tamano del disco principal."
  default     = "20G"
}

variable "memory" {
  type        = number
  description = "Memoria en MB."
  default     = 4096
}

variable "cores" {
  type        = number
  description = "Numero de cores."
  default     = 4
}

variable "sockets" {
  type        = number
  description = "Numero de sockets."
  default     = 1
}

variable "ssh_username" {
  type        = string
  description = "Usuario creado por el autoinstall para SSH."
  default     = "ubuntu"
}

variable "ssh_private_key_file" {
  type        = string
  description = "Ruta al private key usado por Packer para conectarse por SSH."
}

variable "identity_password_hash" {
  type        = string
  sensitive   = true
  description = "Password hash para el usuario del instalador Ubuntu."
}

variable "ssh_public_key_file" {
  type        = string
  description = "Ruta al public key que se inyecta en el autoinstall."
}

variable "ssh_timeout" {
  type        = string
  description = "Tiempo maximo de espera para SSH."
  default     = "30m"
}

variable "template_tags" {
  type        = string
  description = "Tags para la plantilla Proxmox (separadas por punto y coma)."
  default     = "ubuntu26;template"
}
