apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-admin
  namespace: monitoring
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: grafana-admin
    creationPolicy: Owner
  data:
    - secretKey: admin-user
      remoteRef:
        key: grafana/admin
        property: admin-user
    - secretKey: admin-password
      remoteRef:
        key: grafana/admin
        property: admin-password
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc
  namespace: monitoring
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: grafana-oidc
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: grafana/oidc
        property: client-secret
