apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: monitoring

resources:
  - httproute.yml
  - externalsecrets.yml

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    version: 10.5.15
    releaseName: grafana
    namespace: monitoring
    valuesInline:
      persistence:
        enabled: true
        storageClassName: synology-iscsi-storage
        size: 5Gi

      admin:
        existingSecret: grafana-admin
        userKey: admin-user
        passwordKey: admin-password

      envValueFrom:
        GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
          secretKeyRef:
            name: grafana-oidc
            key: client-secret

      grafana.ini:
        server:
          root_url: https://grafana.bonchan.org
        auth.generic_oauth:
          enabled: true
          name: Authentik
          client_id: grafana
          scopes: "openid profile email groups"
          auth_url: https://authentik.bonchan.org/application/o/authorize/
          token_url: https://authentik.bonchan.org/application/o/token/
          api_url: https://authentik.bonchan.org/application/o/userinfo/
          role_attribute_path: "contains(groups[*], 'Grafana Admins') && 'Admin' || contains(groups[*], 'Grafana Editors') && 'Editor' || 'Viewer'"
          role_attribute_strict: false
          auto_login: false

      datasources:
        datasources.yaml:
          apiVersion: 1
          datasources:
            - name: Prometheus
              uid: prometheus
              type: prometheus
              access: proxy
              url: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
              isDefault: true
            - name: Loki
              uid: loki
              type: loki
              access: proxy
              url: http://loki.monitoring.svc.cluster.local:3100

      sidecar:
        dashboards:
          enabled: true
          searchNamespace: ALL
          label: grafana_dashboard
        datasources:
          enabled: false

      dashboardProviders:
        dashboardproviders.yaml:
          apiVersion: 1
          providers:
            - name: default
              orgId: 1
              folder: ""
              type: file
              disableDeletion: false
              editable: true
              options:
                path: /var/lib/grafana/dashboards/default
      dashboards:
        default:
          node-exporter:
            gnetId: 1860
            revision: 37
            datasource: Prometheus
          k8s-views-global:
            gnetId: 15757
            revision: 43
            datasource: Prometheus
          loki-logs:
            gnetId: 13639
            revision: 2
            datasource: Loki

      resources:
        requests:
          cpu: 100m
          memory: 128Mi
        limits:
          memory: 256Mi
