apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
  - pairs:
      app.kubernetes.io/managed-by: Kustomize

resources:
  - namespace.yml
  - gateway.yml
  - https-redirect.yml
  - clienttrafficpolicy.yml
  - security-headers.yml
  - servicemonitors.yml

helmCharts:
  - name: gateway-helm
    repo: oci://docker.io/envoyproxy
    version: 1.8.1
    releaseName: envoy-gateway
    namespace: envoy-gateway-system
    includeCRDs: true
    valuesInline:
      config:
        envoyGateway:
          extensionApis:
            enableBackend: true
      deployment:
        replicas: 2
        pod:
          affinity:
            podAntiAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                - topologyKey: kubernetes.io/hostname
                  labelSelector:
                    matchLabels:
                      control-plane: envoy-gateway
      podDisruptionBudget:
        minAvailable: 1