apiVersion: v1
kind: ConfigMap
metadata:
  name: stalwart-config
  namespace: stalwart
data:
  config.toml: |
    [server]
    hostname = "mail.bonchan.org"

    [server.listener.http]
    bind = ["0.0.0.0:8080"]
    protocol = "http"

    [storage]
    data = "rocksdb"
    fts = "rocksdb"
    blob = "rocksdb"
    lookup = "rocksdb"

    [store.rocksdb]
    type = "rocksdb"
    path = "/opt/stalwart/data"
