apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: stalwart

resources:
  - namespace.yml
  - pvc.yml
  - configmap.yml
  - certificate.yml
  - deployment.yml
  - service.yml
  - service-lb.yml
  - httproute.yml
  - backendtrafficpolicy.yml
