apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: snappymail-data
  namespace: snappymail
  labels:
    app.kubernetes.io/name: snappymail
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-nfs-storage
  resources:
    requests:
      storage: 2Gi
