apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: garage
  namespace: garage
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: garage
  endpoints:
    - port: admin
      path: /metrics
      interval: 30s
      authorization:
        credentials:
          name: garage-secrets
          key: metrics_token
