apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-config
  namespace: media
  labels:
    app.kubernetes.io/name: jellyfin
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-nfs-storage
  resources:
    requests:
      storage: 10Gi
