apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sonarr-config
  namespace: media
  labels:
    app.kubernetes.io/name: sonarr
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  volumeName: pvc-56c5da91-5c4a-42c8-9bc0-8c758cee0866
  resources:
    requests:
      storage: 2Gi
