apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true

  settings.yaml: |
    title: Lakasa Homelab
    favicon: https://gethomepage.dev/img/favicon.ico
    headerStyle: clean
    language: es
    layout:
      Cluster Management:
        style: row
        columns: 4
        icon: si-kubernetes

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23

  services.yaml: |
    []

  bookmarks.yaml: |
    - Homelab:
        - Repositorio:
            - abbr: GH
              href: https://github.com/Jasviers/homelab
        - Proxmox zoro:
            - abbr: PVE
              href: https://zoro.bonchan.org:8006
        - Proxmox nami:
            - abbr: PVE
              href: https://nami.bonchan.org:8006
        - NAS Synology:
            - abbr: NAS
              href: https://nas.bonchan.org

  docker.yaml: ""
  proxmox.yaml: ""
  custom.css: ""
  custom.js: ""
