apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
    gateway: true

  settings.yaml: |
    title: Lakasa Homelab
    favicon: https://gethomepage.dev/img/favicon.ico
    headerStyle: clean
    language: es
    theme: dark
    color: slate
    cardBlur: xs
    background:
      image: https://images.unsplash.com/photo-1502790671504-542ad42d5189?auto=format&fit=crop&w=2560&q=80
      blur: sm
      saturate: 50
      brightness: 50
      opacity: 50
    layout:
      Infraestructura:
        style: row
        columns: 5
      Plataforma:
        style: row
        columns: 4
        icon: si-kubernetes
      Monitorizacion:
        style: row
        columns: 2
      Media:
        style: row
        columns: 3

  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
    - search:
        provider: duckduckgo
        target: _blank
    - datetime:
        text_size: xl
        format:
          dateStyle: long
          timeStyle: short
          hourCycle: h23

  services.yaml: |
    []

  bookmarks.yaml: |
    - Homelab:
        - GItHub:
            - abbr: GH
              href: https://github.com/Jasviers/homelab
        - Home Assistant:
            - abbr: HA
              href: https://hs-lakasa.bonchan.org
        - Pihole:
            - abbr: DNS
              href: http://luffy.bonchan.org/admin
        - NAS Synology:
            - abbr: NAS
              href: https://nas.bonchan.org
        - YouTube:
            - icon: youtube.png
              href: https://youtube.com
        - Cloudflare:
            - icon: cloudflare.png
              href: https://dash.cloudflare.com

  docker.yaml: ""
  proxmox.yaml: ""
  custom.css: ""
  custom.js: ""
