apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hubble-oidc-secret
  namespace: kube-system
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: hubble-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: client-secret
      remoteRef:
        key: hubble/oidc
        property: client-secret
