repositories:
  - name: prometheus-community
    url: https://prometheus-community.github.io/helm-charts
  - name: grafana
    url: https://grafana.github.io/helm-charts
  - name: fluent
    url: https://fluent.github.io/helm-charts

---

releases:
  # Metrics
  - name: prometheus
    namespace: monitor
    chart: prometheus-community/prometheus
    version: 27.3.0
    values:
      - ./values/prometheus.values.yaml

  # logs
  - name: loki
    namespace: monitor
    chart: grafana/loki-stack
    version: 2.10.2
    values:
      - ./values/loki.values.yaml

  - name: fluent-bit
    namespace: monitor
    chart: fluent/fluent-bit
    version: 0.48.6
    values:
      - ./values/fluent.values.yaml

  # traces
  - name: tempo
    namespace: monitor
    chart: grafana/tempo
    version: 1.18.1
 
