apiVersion: v1
kind: Service
metadata:
  name: prometheus-loadbalancer
  namespace: monitor
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/component: server
    app.kubernetes.io/instance: prometheus
    app.kubernetes.io/name: prometheus
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
  loadBalancerIP: 192.168.1.197

---

apiVersion: v1
kind: Service
metadata:
  name: loki-loadbalancer
  namespace: monitor
spec:
  type: LoadBalancer
  selector:
    app: loki
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  loadBalancerIP: 192.168.1.198

---

apiVersion: v1
kind: Service
metadata:
  name: tempo-loadbalancer
  namespace: monitor
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/instance: tempo
    app.kubernetes.io/name: tempo
  ports:
    - protocol: TCP
      port: 3100
      targetPort: 3100
  loadBalancerIP: 192.168.1.199