apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argocd
resources:
- namespace.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
- svc.yaml
- externalsecret-oidc.yml

patches:
- path: argocd-cm-patch.yaml
- path: argocd-cmd-params-patch.yaml
- path: argocd-rbac-cm-patch.yaml
