apiVersion: monitoring.coreos.com/v1
kind: Probe
metadata:
  name: blackbox-icmp-hosts
  namespace: monitoring
spec:
  module: icmp
  interval: 30s
  prober:
    url: blackbox-exporter-prometheus-blackbox-exporter.monitoring.svc.cluster.local:9115
  targets:
    staticConfig:
      labels:
        job: blackbox-icmp
      targets:
        - 192.168.1.1 # nas
        - 192.168.1.2 # luffy
        - 192.168.1.3 # zoro
        - 192.168.1.4 # nami
        - 192.168.0.1 # router asus
        - 192.168.20.1 # router site b
        - 192.168.20.134 # rpi2b site b
