apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: media-library
  namespace: media
  labels:
    app.kubernetes.io/name: media-library
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: synology-iscsi-storage
  resources:
    requests:
      storage: 500Gi
