[homelab]
luffy ansible_host=192.168.1.2
zoro  ansible_host=192.168.1.3
nami  ansible_host=192.168.1.4

[proxmox]
zoro
nami

[raspberry_pi]
luffy

[k3s_control_plane]
192.168.1.21
192.168.1.22

[k3s_workers]
192.168.1.30
192.168.1.31

[k3s_ai]
192.168.1.40

[k8s_cluster:children]
k3s_control_plane
k3s_workers
k3s_ai

[homelab:vars]
ansible_user=root
ansible_ssh_private_key_file=/home/jasviers/.ssh/id_ed25519

[k8s_cluster:vars]
ansible_user=ubuntu
ansible_ssh_private_key_file=/home/jasviers/.ssh/id_ed25519