apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: secret_key
      remoteRef:
        key: authentik/secret-key
        property: secret_key
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-oidc-secrets
  namespace: authentik
spec:
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  refreshInterval: 1h
  target:
    name: authentik-oidc-secrets
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: authentik/oidc
