apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: external-secrets

labels:
  - pairs:
      app.kubernetes.io/managed-by: Kustomize

resources:
  - namespace.yml
  - clustersecretstore.yml

helmCharts:
  - name: external-secrets
    repo: https://charts.external-secrets.io
    version: 2.6.0
    releaseName: external-secrets
    namespace: external-secrets
    valuesInline:
      installCRDs: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
        limits:
          memory: 128Mi
      webhook:
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            memory: 64Mi
      certController:
        resources:
          requests:
            cpu: 25m
            memory: 32Mi
          limits:
            memory: 64Mi
