name: CI pipeline

on:
  push:
    branches:
      - "feature/*"
      - "bugfix/*"
      - "hotfix/*"
  workflow_dispatch:
  workflow_call:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write
  security-events: write

jobs:
  terraform:
    uses: Jasviers/actions/.github/workflows/ci.yml@v2
    with:
      language: terraform
      working-directory: terraform
      run-docker-build: false
      skip-markdown-checks: true
      skip-yamllint: true
      skip-shellcheck: true
      skip-hadolint: true
    secrets: inherit

  ansible:
    uses: Jasviers/actions/.github/workflows/ci.yml@v2
    with:
      language: ansible
      working-directory: ansible
      run-docker-build: false
      skip-markdown-checks: true
      skip-yamllint: true
      skip-shellcheck: true
      skip-hadolint: true
    secrets: inherit

  kubernetes:
    uses: Jasviers/actions/.github/workflows/ci.yml@v2
    with:
      language: kubernetes
      working-directory: services
      run-docker-build: false
      skip-hadolint: true
    secrets: inherit
