name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write
  pages: write
  id-token: write
  security-events: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Make release with quality checks
        uses: Jasviers/actions/make-release@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
