name: Release

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: false

permissions:
  contents: write
  pull-requests: write
  packages: write
  pages: write
  id-token: write

jobs:
  release:
    uses: Jasviers/actions/.github/workflows/release.yml@v2
    with:
      language: none
      run-docker-build: false
      run-docs: false
    secrets: inherit
